server:
  port: 8001
spring:
  application:
    name: Travel002Provider8001provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/travel
    username: root
    password: root
#  thymeleaf:                            #thymelea模板配置
#    cache: false
#    mode: HTML5
#    encoding: UTF-8
#  servlet:
#      content-type: text/html
#    prefix: classpath:/templates/
#    suffix: .html
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
#    static-locations: classpath:/templates/,classpath:/static/
mybatis:
  type-aliases-package: com.jd.pojo
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
    - classpath:com/travel/dao/mapper/*.xml  
eureka:
  client:
    service-url:
      defaultZone: http://10.12.159.23:7001/eureka/
      #defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: Travel002Provider8001
    prefer-ip-address: true   
   # host-info: SpringCloudDemo
info: 
  app.name: Travel002Provider8001-provider
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
      